services:
  # SkillSwap Express API Web Service
  - type: web
    name: skillswap-api
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://bkush535_db_user:ByI7OAgq2yBHQKSG@cluster0.6fguzxo.mongodb.net/skillswap?retryWrites=true&w=majority
      - key: PORT
        value: 5000

  # SkillSwap React Frontend Static Site
  - type: web
    name: skillswap-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: skillswap-api
          property: host
